export const INTERVIEW_TIPS: string[] = [
  "Use the STAR method (Situation, Task, Action, Result) to structure behavioral answers.",
  "Speak clearly and at a steady pace — the AI is transcribing you, so mumbling costs you points.",
  "Think out loud during technical questions; interviewers value your reasoning as much as the answer.",
  "Keep answers focused — aim to fully answer the question in under two minutes.",
  "Start with a short summary of your answer, then back it up with specifics.",
  "Use concrete numbers and outcomes when describing past projects (e.g. \"reduced load time by 40%\").",
  "Avoid filler words like \"um\" and \"like\" — brief pauses read as confidence, not hesitation.",
  "Research the role and company context before your session so your examples feel relevant.",
  "Practice explaining trade-offs, not just the final decision you made.",
  "If you don't know something, say so honestly and explain how you'd find out.",
  "Maintain eye contact with the camera, not the screen, to simulate real interview presence.",
  "Sit in a quiet, well-lit space — background noise can affect transcription quality.",
  "Restate the question briefly before answering to make sure you understood it correctly.",
  "For technical questions, mention time/space complexity or scalability where relevant.",
  "End answers with a clear conclusion instead of trailing off.",
  "Prepare 2-3 strong project stories you can adapt to different behavioral questions.",
  "Show enthusiasm — tone and energy come through even in a transcript-based evaluation.",
  "Don't rush; a well-paced answer is easier to follow than a fast, cramped one.",
  "Use \"I\" statements to be clear about your individual contribution on team projects.",
  "Review your previous interview feedback before starting a new session.",
  "Take a breath before answering — a short pause to organize your thoughts is completely fine.",
  "Treat every mock interview like the real thing; the habits you build here carry over.",
  "Close weak answers with what you learned, not just what went wrong.",
];
