"use client";

import { useState, useMemo } from "react";
import { ArrowDownTrayIcon, SparklesIcon } from "@heroicons/react/24/outline";

type TemplateKey = "modern" | "classic" | "creative" | "minimal";

function ResumePreview({
  template,
  data,
}: {
  template: TemplateKey;
  data: {
    fullName: string;
    email: string;
    phone: string;
    location: string;
    summary: string;
    experience: string;
    education: string;
  };
}) {
  const { fullName, email, phone, location, summary, experience, education } =
    data;

  const variant = useMemo(() => {
    switch (template) {
      case "classic":
        return {
          headingClass: "text-2xl font-bold text-gray-900",
          accent: "border-l-4 border-yellow-300 pl-4",
          bg: "bg-white",
        };
      case "creative":
        return {
          headingClass: "text-2xl font-extrabold text-yellow-800",
          accent: "bg-gradient-to-r from-yellow-100 to-yellow-50 p-4 rounded",
          bg: "bg-white",
        };
      case "minimal":
        return {
          headingClass: "text-xl font-semibold text-gray-800",
          accent: "text-gray-700",
          bg: "bg-white",
        };
      case "modern":
      default:
        return {
          headingClass: "text-2xl font-bold text-gray-800",
          accent: "flex items-center gap-4",
          bg: "bg-white",
        };
    }
  }, [template]);

  return (
    <div className={`rounded-xl border border-gray-100 p-6 ${variant.bg}`}>
      <div className={variant.accent}>
        <div className={variant.headingClass}>{fullName || "Full Name"}</div>
        <div className="text-sm text-gray-600 mt-1">
          {email || "email@example.com"} • {phone || "Phone"} •{" "}
          {location || "Location"}
        </div>
      </div>

      <section className="mt-4">
        <h4 className="text-sm font-semibold text-gray-700">
          Professional Summary
        </h4>
        <p className="text-sm text-gray-600 mt-1">
          {summary ||
            "Short, crisp summary that highlights skills, goals and impact."}
        </p>
      </section>

      <section className="mt-4 grid grid-cols-1 gap-3">
        <div>
          <h4 className="text-sm font-semibold text-gray-700">Experience</h4>
          <p className="text-sm text-gray-600 mt-1">
            {experience ||
              "Role • Company • Achievements (use numbers where possible)"}
          </p>
        </div>

        <div>
          <h4 className="text-sm font-semibold text-gray-700">Education</h4>
          <p className="text-sm text-gray-600 mt-1">
            {education || "Degree • Institution • Year"}
          </p>
        </div>
      </section>
    </div>
  );
}

export default function ResumeBuilderPage() {
  const [template, setTemplate] = useState<TemplateKey>("modern");

  const [fullName, setFullName] = useState("");
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const [location, setLocation] = useState("");
  const [summary, setSummary] = useState("");
  const [experience, setExperience] = useState("");
  const [education, setEducation] = useState("");

  const handleAIEnhance = (setter: (value: string) => void, value: string) => {
    setter(value ? `${value} — polished by AI` : "Generated by AI.");
  };

  const handleDownload = () => {
    alert("Download PDF - integrate react-to-print or jsPDF (TODO)");
  };

  return (
    <div className="min-h-screen bg-white px-12 py-8">
      <main className="w-full px-2 sm:px-4 lg:px-6">
        {/* Heading + Dropdown */}
        <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-4">
          <div className="flex flex-col items-start justify-start gap-2">
            <h1 className="text-3xl font-bold text-gray-800">
              Smart resume builder
            </h1>
            <p className="text-lg text-yellow-900">
              Build smarter resumes with AI and stand out from the competition
            </p>
          </div>
        </div>

        {/* Content area */}
        <div className="mt-6 grid grid-cols-1 lg:grid-cols-[1.5fr_2fr] gap-6">
          {/* LEFT: Form */}
          <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100 space-y-4">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-sm font-medium text-gray-700">
                  Full Name
                </label>
                <input
                  value={fullName}
                  onChange={(e) => setFullName(e.target.value)}
                  className="mt-2 w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-yellow-200"
                  placeholder="John Doe"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">
                  Location
                </label>
                <input
                  value={location}
                  onChange={(e) => setLocation(e.target.value)}
                  className="mt-2 w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-yellow-200"
                  placeholder="New York, NY"
                />
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-sm font-medium text-gray-700">
                  Email
                </label>
                <input
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className="mt-2 w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-yellow-200"
                  placeholder="you@example.com"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">
                  Phone
                </label>
                <input
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                  className="mt-2 w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-yellow-200"
                  placeholder="+1 (555) 123-4567"
                />
              </div>
            </div>

            {/* Summary */}
            <div>
              <div className="flex items-center justify-between">
                <label className="block text-sm font-medium text-gray-700">
                  Professional Summary
                </label>
                <button
                  onClick={() => handleAIEnhance(setSummary, summary)}
                  className="flex items-center gap-1 px-2 py-1 rounded-md text-xs font-medium text-gray-800 bg-gradient-to-r from-purple-100 via-pink-100 to-orange-100 shadow-sm hover:shadow-md transition-transform transform hover:-translate-y-0.5 hover:brightness-105"
                >
                  <SparklesIcon className="w-3 h-3 text-pink-500" /> AI Enhance
                </button>
              </div>
              <textarea
                value={summary}
                onChange={(e) => setSummary(e.target.value)}
                rows={4}
                className="mt-2 w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-yellow-200"
                placeholder="Write a short summary..."
              />
            </div>

            {/* Experience */}
            <div>
              <div className="flex items-center justify-between">
                <label className="block text-sm font-medium text-gray-700">
                  Experience
                </label>
                <button
                  onClick={() => handleAIEnhance(setExperience, experience)}
                  className="flex items-center gap-1 px-2 py-1 rounded-md text-xs font-medium text-gray-800 bg-gradient-to-r from-purple-100 via-pink-100 to-orange-100 shadow-sm hover:shadow-md transition-transform transform hover:-translate-y-0.5 hover:brightness-105"
                >
                  <SparklesIcon className="w-3 h-3 text-pink-500" /> AI Enhance
                </button>
              </div>
              <textarea
                value={experience}
                onChange={(e) => setExperience(e.target.value)}
                rows={4}
                className="mt-2 w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-yellow-200"
                placeholder="Your experience..."
              />
            </div>

            {/* Education */}
            <div>
              <div className="flex items-center justify-between">
                <label className="block text-sm font-medium text-gray-700">
                  Education
                </label>
                <button
                  onClick={() => handleAIEnhance(setEducation, education)}
                  className="flex items-center gap-1 px-2 py-1 rounded-md text-xs font-medium text-gray-800 bg-gradient-to-r from-purple-100 via-pink-100 to-orange-100 shadow-sm hover:shadow-md transition-transform transform hover:-translate-y-0.5 hover:brightness-105"
                >
                  <SparklesIcon className="w-3 h-3 text-pink-500" /> AI Enhance
                </button>
              </div>
              <textarea
                value={education}
                onChange={(e) => setEducation(e.target.value)}
                rows={3}
                className="mt-2 w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-yellow-200"
                placeholder="Your education..."
              />
            </div>

            {/* Actions */}
            <div className="flex items-center gap-3 mt-2">
              <button
                onClick={handleDownload}
                className="bg-yellow-400 hover:bg-yellow-500 px-4 py-2 rounded-lg text-sm font-semibold shadow flex items-center gap-2"
              >
                <ArrowDownTrayIcon className="w-4 h-4" /> Download PDF
              </button>
            </div>
          </div>

          <div className="space-y-6">
            <div className="sticky top-24">
              {/* Card container */}
              <div className="bg-green-100/40 shadow-md rounded-2xl  border border-gray-100 p-6 space-y-4">
                {/* Header with text and select */}
                <div className="flex items-center justify-between">
                  <div className="text-sm font-semibold text-gray-700">
                    Template Preview
                  </div>
                  <div className="relative inline-block">
                    <select
                      value={template}
                      onChange={(e) =>
                        setTemplate(e.target.value as TemplateKey)
                      }
                      className="appearance-none px-4 py-2 pr-10 rounded-lg border border-gray-300 bg-white shadow-sm text-gray-700 text-sm font-medium focus:outline-none focus:ring-2 focus:ring-yellow-300 focus:border-yellow-300 transition-all cursor-pointer hover:shadow-md"
                    >
                      <option value="modern">Modern</option>
                      <option value="classic">Classic</option>
                      <option value="creative">Creative</option>
                      <option value="minimal">Minimal</option>
                    </select>
                    <svg
                      className="w-4 h-4 absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 pointer-events-none"
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M19 9l-7 7-7-7"
                      />
                    </svg>
                  </div>
                </div>

                {/* Resume Preview */}
                <ResumePreview
                  template={template}
                  data={{
                    fullName,
                    email,
                    phone,
                    location,
                    summary,
                    experience,
                    education,
                  }}
                />
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
