import { Student } from "@/components/StudentsTable";

export const MOCK_STUDENTS: Student[] = [
  {
    id: "stu-001",
    name: "Arjun Reddy",
    email: "arjun.reddy@iitb.ac.in",
    rollNo: "CSE25A001",
    status: "active",
    joinedAt: "2024-07-12",
    quizzesTaken: 18,
    aiInterviews: 4,
    resumesMade: 3,
    codingAttempts: 120,
  },
  {
    id: "stu-002",
    name: "Ananya Iyer",
    email: "ananya.iyer@iitb.ac.in",
    rollNo: "CSE25A002",
    status: "active",
    joinedAt: "2024-07-13",
    quizzesTaken: 22,
    aiInterviews: 6,
    resumesMade: 5,
    codingAttempts: 160,
  },
  {
    id: "stu-003",
    name: "Karthik Subramanian",
    email: "karthik.subramanian@iitb.ac.in",
    rollNo: "CSE25A003",
    status: "inactive",
    joinedAt: "2024-07-15",
    quizzesTaken: 9,
    aiInterviews: 1,
    resumesMade: 1,
    codingAttempts: 40,
  },
  {
    id: "stu-004",
    name: "Priya Natarajan",
    email: "priya.natarajan@iitb.ac.in",
    rollNo: "CSE25A004",
    status: "active",
    joinedAt: "2024-07-16",
    quizzesTaken: 25,
    aiInterviews: 7,
    resumesMade: 6,
    codingAttempts: 180,
  },
  {
    id: "stu-005",
    name: "Suresh Kumar",
    email: "suresh.kumar@iitb.ac.in",
    rollNo: "CSE25A005",
    status: "active",
    joinedAt: "2024-07-18",
    quizzesTaken: 14,
    aiInterviews: 3,
    resumesMade: 2,
    codingAttempts: 95,
  },
  {
    id: "stu-006",
    name: "Divya Srinivasan",
    email: "divya.srinivasan@iitb.ac.in",
    rollNo: "CSE25A006",
    status: "active",
    joinedAt: "2024-07-20",
    quizzesTaken: 30,
    aiInterviews: 8,
    resumesMade: 7,
    codingAttempts: 210,
  },
  {
    id: "stu-007",
    name: "Vignesh Raman",
    email: "vignesh.raman@iitb.ac.in",
    rollNo: "CSE25A007",
    status: "inactive",
    joinedAt: "2024-07-21",
    quizzesTaken: 6,
    aiInterviews: 0,
    resumesMade: 1,
    codingAttempts: 25,
  },
  {
    id: "stu-008",
    name: "Meera Krishnan",
    email: "meera.krishnan@iitb.ac.in",
    rollNo: "CSE25A008",
    status: "active",
    joinedAt: "2024-07-22",
    quizzesTaken: 19,
    aiInterviews: 5,
    resumesMade: 4,
    codingAttempts: 140,
  },
  {
    id: "stu-009",
    name: "Rohit Balakrishnan",
    email: "rohit.b@iitb.ac.in",
    rollNo: "CSE25A009",
    status: "active",
    joinedAt: "2024-07-23",
    quizzesTaken: 21,
    aiInterviews: 6,
    resumesMade: 5,
    codingAttempts: 155,
  },
  {
    id: "stu-010",
    name: "Lakshmi Menon",
    email: "lakshmi.menon@iitb.ac.in",
    rollNo: "CSE25A010",
    status: "active",
    joinedAt: "2024-07-24",
    quizzesTaken: 16,
    aiInterviews: 3,
    resumesMade: 3,
    codingAttempts: 110,
  },
  {
    id: "stu-011",
    name: "Naveen Chandra",
    email: "naveen.chandra@iitb.ac.in",
    rollNo: "CSE25A011",
    status: "inactive",
    joinedAt: "2024-07-25",
    quizzesTaken: 8,
    aiInterviews: 1,
    resumesMade: 1,
    codingAttempts: 50,
  },
  {
    id: "stu-012",
    name: "Shreya Raghavan",
    email: "shreya.raghavan@iitb.ac.in",
    rollNo: "CSE25A012",
    status: "active",
    joinedAt: "2024-07-26",
    quizzesTaken: 27,
    aiInterviews: 7,
    resumesMade: 6,
    codingAttempts: 195,
  },
];

export const MOCK_CONTEXT = {
  collegeName: "IIT Bombay",
  branchName: "Computer Science",
  ccgName: "CSE 2025 - Group A",
  academicYear: "2025",
};
